### ISSUE TITLE
Update README.md to finish version

### ISSUE THREAD

**Issue by AlexanderTirik** [AlexanderTirik/homepage#25]
Update README.md to finish version

**Comment by AnnaKoroliuk** [comment]
# Homepage
My very own personal website. Basically this is just a résumé.🏗

# Usage

If Ilon Musk sees this resume, he will use it as the main one. 😼

# License
MIT License

Copyright (c) 2020

**Comment by AlexanderTirik** [comment]
Thank you so much!
