### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by AlexanderTirik** [AlexanderTirik/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by TirikAlexander** [comment]
The real-life Iron Man. Got the full 6-month Commodore manual in 3 days, made a game, sold it for 500$. At age 12.  Lived on 1$/day during college, eating mostly hot dogs to learn money doesn't really matter. Gave 3 engagement rings to my wife Tallulah, one of which I designed.

**Comment by AlexanderTirik** [comment]
The real-life Iron Man. Got the full 6-month Commodore manual in 3 days, made a game, sold it for 500$. At age 12. Lived on 1$/day during college, eating mostly hot dogs to learn money doesn't really matter. Gave 3 engagement rings to my wife Tallulah, one of which I designed.
